# Generated by Django 5.1.8 on 2025-05-23 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreta", "0001_initial"),
        ("materia", "0004_remove_detallemateria_usuario_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="libreta",
            old_name="usuario",
            new_name="estudiante",
        ),
        migrations.AddField(
            model_name="libreta",
            name="detalle_materia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="libretas",
                to="materia.detallemateria",
            ),
        ),
    ]
