# Generated by Django 5.1.8 on 2025-06-10 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libreta", "0001_initial"),
        ("materia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="libreta",
            name="detalle_materia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="libretas",
                to="materia.detallemateria",
            ),
        ),
    ]
