# Generated by Django 5.1.8 on 2025-05-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreta", "0002_rename_usuario_libreta_estudiante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="libreta",
            name="nota",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
