# Generated by Django 5.1.8 on 2025-06-08 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libreta", "0003_libreta_nota"),
        ("materia", "0011_remove_asistencia_alumno_detallemateria_actividad_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrediccionNota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ser", models.FloatField(blank=True, null=True)),
                ("saber", models.FloatField(blank=True, null=True)),
                ("hacer", models.FloatField(blank=True, null=True)),
                ("decidir", models.FloatField(blank=True, null=True)),
                ("nota_predicha", models.DecimalField(decimal_places=2, max_digits=5)),
                ("estado_predicho", models.CharField(max_length=20)),
                ("fecha_prediccion", models.DateTimeField(auto_now_add=True)),
                (
                    "detalle_materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicciones",
                        to="materia.detallemateria",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "libreta",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicciones",
                        to="libreta.libreta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predicción de Nota",
                "verbose_name_plural": "Predicciones de Notas",
            },
        ),
    ]
