# Generated by Django 5.1.8 on 2025-06-10 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actividad", "0001_initial"),
        ("materia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleactividad",
            name="detalle_materia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_actividad",
                to="materia.detallemateria",
            ),
        ),
        migrations.AddField(
            model_name="actividad",
            name="dimension",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades",
                to="actividad.dimension",
            ),
        ),
        migrations.AddField(
            model_name="entregatarea",
            name="actividad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entregas",
                to="actividad.actividad",
            ),
        ),
    ]
