# Generated by Django 5.1.8 on 2025-05-28 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actividad", "0001_initial"),
        ("materia", "0006_detallemateria_curso"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividad",
            name="detalle_materia",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades",
                to="materia.detallemateria",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="actividad",
            name="fecha",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="DetalleActividad",
        ),
    ]
