# Generated by Django 5.1.8 on 2025-05-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actividad", "0002_actividad_detalle_materia_actividad_fecha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividad",
            name="calificacion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
