# Generated by Django 5.2.1 on 2025-05-31 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_actividad_fechacreacion_entregatarea'),
        ('materia', '0008_remove_detallemateria_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleactividad',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='detalleactividad',
            name='usuario',
        ),
        migrations.AddField(
            model_name='detalleactividad',
            name='detalle_materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_actividad', to='materia.detallemateria'),
            preserve_default=False,
        ),
    ]
