# Generated by Django 5.2.1 on 2025-05-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0003_remove_detalleactividad_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregatarea',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
