# Generated by Django 5.1.8 on 2025-06-06 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actividad", "0004_entregatarea"),
        ("actividad", "0004_entregatarea_entregado"),
    ]

    operations = []
