# Generated by Django 5.1.8 on 2025-06-06 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actividad", "0005_merge_0004_entregatarea_0004_entregatarea_entregado"),
        ("materia", "0010_merge_20250605_2222"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actividad",
            name="calificacion",
        ),
        migrations.RemoveField(
            model_name="actividad",
            name="detalle_materia",
        ),
        migrations.RemoveField(
            model_name="actividad",
            name="fecha",
        ),
        migrations.AddField(
            model_name="entregatarea",
            name="entregado",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DetalleActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles_actividad",
                        to="actividad.actividad",
                    ),
                ),
                (
                    "detalle_materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles_actividad",
                        to="materia.detallemateria",
                    ),
                ),
            ],
        ),
    ]
