# Generated by Django 5.1.8 on 2025-05-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_permiso_rol_alter_usuario_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="codigo",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
