# Generated by Django 5.1.8 on 2025-05-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_usuario_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="ci",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="codigo",
            field=models.BigIntegerField(unique=True),
        ),
    ]
