# Generated by Django 5.2.1 on 2025-06-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_ci_alter_usuario_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
