# Generated by Django 5.1.8 on 2025-05-23 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actividad", "0001_initial"),
        (
            "materia",
            "0002_actividad_dimension_detalleactividad_detallemateria_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actividad",
            name="dimension",
        ),
        migrations.RemoveField(
            model_name="detalleactividad",
            name="actividad",
        ),
        migrations.AlterField(
            model_name="detallemateria",
            name="actividad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detalles_materia",
                to="actividad.actividad",
            ),
        ),
        migrations.RemoveField(
            model_name="detalleactividad",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="Dimension",
        ),
        migrations.DeleteModel(
            name="Actividad",
        ),
        migrations.DeleteModel(
            name="DetalleActividad",
        ),
    ]
