# Generated by Django 5.1.8 on 2025-05-23 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materia", "0003_remove_actividad_dimension_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detallemateria",
            name="usuario",
        ),
        migrations.AddField(
            model_name="detallemateria",
            name="profesor",
            field=models.ForeignKey(
                blank=True,
                help_text="Profesor asignado a la materia",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_materia",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
