# Generated by Django 5.1.8 on 2025-05-25 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curso", "0001_initial"),
        ("materia", "0005_alter_detallemateria_profesor"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallemateria",
            name="curso",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_materia",
                to="curso.curso",
            ),
            preserve_default=False,
        ),
    ]
