# Generated by Django 5.2.1 on 2025-05-30 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0006_detallemateria_curso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
