# Generated by Django 5.1.8 on 2025-05-28 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curso", "0001_initial"),
        ("materia", "0006_detallemateria_curso"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detallemateria",
            name="actividad",
        ),
        migrations.AlterField(
            model_name="detallemateria",
            name="curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_materia",
                to="curso.curso",
            ),
        ),
    ]
