# Generated by Django 5.1.8 on 2025-05-31 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materia", "0007_remove_detallemateria_actividad_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="alumno",
            field=models.ForeignKey(
                default=1,
                help_text="Alumno relacionado con la asistencia",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asistencias",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
