# Generated by Django 5.2.1 on 2025-05-31 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0007_asistencia_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallemateria',
            name='actividad',
        ),
    ]
