# Generated by Django 5.2.1 on 2025-05-31 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0003_remove_detalleactividad_fecha_and_more'),
        ('materia', '0008_remove_detallemateria_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemateria',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_materia', to='actividad.actividad'),
        ),
    ]
