# Generated by Django 5.1.8 on 2025-06-06 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materia", "0008_asistencia_alumno"),
        ("materia", "0009_detallemateria_actividad"),
    ]

    operations = []
