# Generated by Django 5.2.1 on 2025-06-07 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0009_detallemateria_actividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionAsistenciaMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de 6 dígitos', max_length=6, unique=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(help_text='Cuando expira la sesión')),
                ('activa', models.BooleanField(default=True)),
                ('duracion_minutos', models.IntegerField(default=15, help_text='Duración en minutos')),
                ('total_registros', models.IntegerField(default=0, help_text='Cuántos estudiantes se registraron')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('detalle_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_movil', to='materia.detallemateria')),
            ],
            options={
                'verbose_name': 'Sesión de Asistencia Móvil',
                'verbose_name_plural': 'Sesiones de Asistencia Móvil',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistenciaMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ubicacion_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('ubicacion_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_movil', to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='materia.sesionasistenciamovil')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia Móvil',
                'verbose_name_plural': 'Registros de Asistencia Móvil',
                'ordering': ['-fecha_registro'],
                'unique_together': {('sesion', 'estudiante')},
            },
        ),
    ]
