# Generated by Django 5.1.8 on 2025-06-06 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actividad", "0006_remove_actividad_calificacion_and_more"),
        ("curso", "0001_initial"),
        ("materia", "0010_merge_20250605_2222"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asistencia",
            name="alumno",
        ),
        migrations.AddField(
            model_name="detallemateria",
            name="actividad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detalles_materia",
                to="actividad.actividad",
            ),
        ),
        migrations.AlterField(
            model_name="detallemateria",
            name="curso",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_materia",
                to="curso.curso",
            ),
            preserve_default=False,
        ),
    ]
